envVariables:
  EXAMPLE: Welcome!
  # THIS MUST BE REPLACED BY YOUR OWN SECRET
  AUTH_SECRET: 'vault:secret/data/luna/boilerplate#AUTH_SECRET'
  AUTH_URL: 'https://luna-boilerplate.int.prd.jspaas.uk'
  AUTH_MICROSOFT_ENTRA_ID_TENANT_ID: e11fd634-26b5-47f4-8b8c-908e466e9bdf
  AUTH_MICROSOFT_ENTRA_ID_CLIENT_ID: b1eb1ab3-d330-44f9-8ec3-a16a413af0b7
  NEW_RELIC_APP_NAME: web-application-template
