envVariables:
  NODE_ENV: production
  NEXTAUTH_URL: 'https://ticketing-app.int.dev.jspaas.uk'
  API_BASE_URL: 'vault:secret/data/team-nucleus/ticketing-app#API_BASE_URL_DEV'
  API_USERNAME: 'vault:secret/data/team-nucleus/ticketing-app#API_USERNAME'
  API_PASSWORD: 'vault:secret/data/team-nucleus/ticketing-app#API_PASSWORD'
  AUTH_SECRET: 'vault:secret/data/team-nucleus/ticketing-app#AUTH_SECRET'
  AUTH_MICROSOFT_ENTRA_ID_TENANT_ID: 'vault:secret/data/team-nucleus/ticketing-app#AUTH_MICROSOFT_ENTRA_ID_TENANT_ID'
  AUTH_MICROSOFT_ENTRA_ID_CLIENT_ID: 'vault:secret/data/team-nucleus/ticketing-app#AUTH_MICROSOFT_ENTRA_ID_CLIENT_ID_DEV'
  ENABLE_HSTS: 'false'
